Controllers/DespachosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ejecuciones.Data;
using Ejecuciones.Models;

namespace Ejecuciones.Controllers
{
    public class DespachosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DespachosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Despachos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Despacho.ToListAsync());
        }

        // GET: Despachos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despacho = await _context.Despacho
                .FirstOrDefaultAsync(m => m.DespachoId == id);
            if (despacho == null)
            {
                return NotFound();
            }

            return View(despacho);
        }

        // GET: Despachos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Despachos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DespachoId,NombreDespacho")] Despacho despacho)
        {
            if (ModelState.IsValid)
            {
                _context.Add(despacho);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(despacho);
        }

        // GET: Despachos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despacho = await _context.Despacho.FindAsync(id);
            if (despacho == null)
            {
                return NotFound();
            }
            return View(despacho);
        }

        // POST: Despachos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DespachoId,NombreDespacho")] Despacho despacho)
        {
            if (id != despacho.DespachoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(despacho);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DespachoExists(despacho.DespachoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(despacho);
        }

        // GET: Despachos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despacho = await _context.Despacho
                .FirstOrDefaultAsync(m => m.DespachoId == id);
            if (despacho == null)
            {
                return NotFound();
            }

            return View(despacho);
        }

        // POST: Despachos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var despacho = await _context.Despacho.FindAsync(id);
            _context.Despacho.Remove(despacho);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DespachoExists(int id)
        {
            return _context.Despacho.Any(e => e.DespachoId == id);
        }
    }
}

Controllers/ProcesosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ejecuciones.Data;
using Ejecuciones.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Ejecuciones.Helpers;

namespace Ejecuciones.Controllers
{
    public class ProcesosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ProcesosController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        // GET: Procesos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Proceso.Include(p => p.Despacho).Include(p => p.EstadoProceso).Include(p => p.Fallador);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Procesos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proceso = await _context.Proceso
                .Include(p => p.Despacho)
                .Include(p => p.EstadoProceso)
                .Include(p => p.Fallador)
                .FirstOrDefaultAsync(m => m.ProcesoId == id);
            if (proceso == null)
            {
                return NotFound();
            }

            return View(proceso);
        }

        // GET: Procesos/Create
        public IActionResult Create()
        {
            ViewData["DespachoId"] = new SelectList(_context.Despacho, "DespachoId", "NombreDespacho");
            ViewData["EstadoProcesoId"] = new SelectList(_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso");
            ViewData["FalladorId"] = new SelectList(_context.Fallador, "FalladorId", "JuzgadoFallador");
            return View();
        }

        // POST: Procesos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        //public async Task<IActionResult> Create([Bind("ProcesoId,DespachoId,FechaProceso,RadicadoProceso,FalladorId,AnexosSolicitud,CuadernosProceso,FoliosProceso,EstadoProcesoId")] Proceso proceso)
        public async Task<IActionResult> Create(Proceso proceso)
        {
            if (ModelState.IsValid)
            {

                if (proceso.ProcesoPdf != null)
                {
                    string folder = @"procesos\";
                    UploadFiles uploadFiles = new UploadFiles();
                    proceso.AnexosProceso = await uploadFiles.UploadPDF(webHostEnvironment, folder, proceso.ProcesoPdf);
                }

                proceso.FechaProceso = DateTime.Now;
                //solicitud.DespachoId = (_context.Despacho, "DspachoId", "NombreDespacho" = 'SECRETARIA CENTRO DE SERVICIOS');
                proceso.DespachoId = 5;
                //solicitud.EstadoProcesoId = (_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso" = 'SIN REPARTIR');
                proceso.EstadoProcesoId = 5;

                _context.Add(proceso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DespachoId"] = new SelectList(_context.Despacho, "DespachoId", "NombreDespacho", proceso.DespachoId);
            ViewData["EstadoProcesoId"] = new SelectList(_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso", proceso.EstadoProcesoId);
            ViewData["FalladorId"] = new SelectList(_context.Fallador, "FalladorId", "JuzgadoFallador", proceso.FalladorId);
            return View(proceso);
        }

        // GET: Procesos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proceso = await _context.Proceso.FindAsync(id);
            if (proceso == null)
            {
                return NotFound();
            }
            ViewData["DespachoId"] = new SelectList(_context.Despacho, "DespachoId", "NombreDespacho", proceso.DespachoId);
            ViewData["EstadoProcesoId"] = new SelectList(_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso", proceso.EstadoProcesoId);
            ViewData["FalladorId"] = new SelectList(_context.Fallador, "FalladorId", "JuzgadoFallador", proceso.FalladorId);
            return View(proceso);
        }

        // POST: Procesos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("ProcesoId,DespachoId,FechaProceso,RadicadoProceso,FalladorId,AnexosSolicitud,CuadernosProceso,FoliosProceso,EstadoProcesoId")] Proceso proceso)
        public async Task<IActionResult> Edit(int id, Proceso proceso)
        {
            if (id != proceso.ProcesoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (proceso.ProcesoPdf != null)
                    {
                        string folder = @"procesos\";
                        UploadFiles uploadFiles = new UploadFiles();
                        proceso.AnexosProceso = await uploadFiles.UploadPDF(webHostEnvironment, folder, proceso.ProcesoPdf);
                    }
                    else
                    {
                        ViewData["DespachoId"] = new SelectList(_context.Despacho, "DespachoId", "NombreDespacho", proceso.DespachoId);
                        ViewData["EstadoProcesoId"] = new SelectList(_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso", proceso.EstadoProcesoId);
                        ViewData["FalladorId"] = new SelectList(_context.Fallador, "FalladorId", "JuzgadoFallador", proceso.FalladorId);
                        return View(proceso);
                    }

                    proceso.FechaProceso = DateTime.Now;
                    //solicitud.DespachoId = (_context.Despacho, "DspachoId", "NombreDespacho" = 'SECRETARIA CENTRO DE SERVICIOS');
                    proceso.DespachoId = 5;
                    //solicitud.EstadoProcesoId = (_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso" = 'SIN REPARTIR');
                    proceso.EstadoProcesoId = 5;

                    _context.Update(proceso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProcesoExists(proceso.ProcesoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DespachoId"] = new SelectList(_context.Despacho, "DespachoId", "NombreDespacho", proceso.DespachoId);
            ViewData["EstadoProcesoId"] = new SelectList(_context.EstadoProceso, "EstadoProcesoId", "NombreEstadoProceso", proceso.EstadoProcesoId);
            ViewData["FalladorId"] = new SelectList(_context.Fallador, "FalladorId", "JuzgadoFallador", proceso.FalladorId);
            return View(proceso);
        }

        // GET: Procesos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proceso = await _context.Proceso
                .Include(p => p.Despacho)
                .Include(p => p.EstadoProceso)
                .Include(p => p.Fallador)
                .FirstOrDefaultAsync(m => m.ProcesoId == id);
            if (proceso == null)
            {
                return NotFound();
            }

            return View(proceso);
        }

        // POST: Procesos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proceso = await _context.Proceso.FindAsync(id);
            _context.Proceso.Remove(proceso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProcesoExists(int id)
        {
            return _context.Proceso.Any(e => e.ProcesoId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSA - JEPMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/Bootstrap.yeti.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>

        <a class="navbar-brand" href="index.html"> <img src="images/logorama.png" alt="Logo" style="width:10em; height:3em"> </a>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background-color: #236093 !important;">
            <div class="container" style="color:white !important;">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapsed-sm-inline justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Datos Maestros
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-white" asp-area="" asp-controller="CargoEmpleados" asp-action="Index">Cargo Empleados</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="Despachos" asp-action="Index">Despachos</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="EstadoProcesos" asp-action="Index">Estados Proceso</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="EstadoSolicitudes" asp-action="Index">Estados Solicitud</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="Falladores" asp-action="Index">Falladores</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionarios</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="Municipios" asp-action="Index">Municipios</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="TipoSolicitudes" asp-action="Index">Tipos Solicitud</a>
                                <a class="dropdown-item text-white" asp-area="" asp-controller="UsuariosRoles" asp-action="Index">Usuarios y Roles</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Solicitudes" asp-action="Index">Registrar Solicitud</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Procesos" asp-action="Index">Cargar Proceso</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Página Principal</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <section id="footer">
            <div class="container">
                <div class="row text-center text-xs-center text-sm-left text-md-left">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <h5>Enlaces</h5>
                        <ul class="list-unstyled quick-links">
                            <li><a href="#"><i class="fa fa-angle-double-right"></i>Rama Judicial</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right"></i>Seccional Caldas</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right"></i>Directorio Judicial Seccional Caldas</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <h5>Ubicación</h5>
                        <ul class="list-unstyled quick-links">
                            <li><a href="#"><i class="fa fa-angle-double-right"></i>Calle 27 # 17-21 Piso 4 Oficina 401 </a></li>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <h5>Contacto</h5>
                        <ul class="list-unstyled quick-links">
                            <li><a href="#"><i class="fa fa-angle-double-right"></i><strong>Teléfono: </strong>(57)(6) 8721752</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right"></i><strong>Celular: </strong>(57)(319) 399 4778</a></li>
                            <li><a href= href="mailto:cserepma@cendoj.ramajudicial.gov.co"><i class="fa fa-angle-double-right"></i><strong>Email: </strong>cserepma@cendoj.ramajudicial.gov.co</a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                        <ul class="list-unstyled list-inline social text-center">
                            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li class="list-inline-item"><a href="#" target="_blank"><i class="fa fa-envelope"></i></a></li>
                        </ul>
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                        <p>Diseño: Ingeniera Nyllireth Betancur Aguirre</p>
                        <p class="h6">© 2021 - CSA Manizales <a class="text-green ml-2" href="#" target="_blank"></a></p>
                    </div>
                    <hr>
                </div>
            </div>
        </section>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>